<?php
  $this->layout()->breadcrumbs = false;
?>
<h2><?=$this->transEsc('An error has occurred')?></h2>
<p class="alert alert-danger"><?=$this->transEsc($this->message)?></p>
<h3 style="text-align:center">You seem to have taken a wrong turn. Here there be dragons.</h3>
<div class="row">
  <div class="col-md-6">
    <a href="https://digital.library.villanova.edu/Item/vudl:14135">
      <img src="https://digital.library.villanova.edu/files/vudl:14135/MEDIUM" style="float:right"></img>
    </a>
  </div>
  <div class="span6">
    <a href="https://digital.library.villanova.edu/Item/vudl:14133">
      <img src="https://digital.library.villanova.edu/files/vudl:14133/MEDIUM" style="float:left"></img>
    </a>
  </div>
</div>
<p style="margin-top:1rem;text-align:right">Exits are <a href="javascript:history.back()">back</a>, <a href="<?=$this->url('home') ?>">search</a>, and <a href="https://digital.library.villanova.edu/Item/vudl:13009">North</a>.</p>
