<li><a href="<?=$this->url('home') ?>">Home</a></li>
<li><a href="<?=$this->url('vudl-default-collection') ?>">Collections</a></li>
<li class="dropdown">
  <a data-toggle="dropdown" href="#">In <?=count($breadcrumbs) ?> Collections</a>
  <div class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <?php foreach ($breadcrumbs as $trail): ?>
      <ul class="sub-breadcrumb">
      <?php foreach ($trail as $id => $title): ?>
        <li><a href="<?=$this->escapeHtmlAttr($this->url('vudl-record', compact('id')))?>"><?=$this->escapeHtml($title) ?></a></li>
      <?php endforeach; ?>
      </ul>
    <?php endforeach; ?>
  </div>
</li>
<?php if (isset($end)): ?>
  <li title="<?=$this->escapeHtmlAttr($title) ?>"><?=$this->escapeHtml($this->truncate($title, 100)) ?></li>
  <li class="active"><?=$this->escapeHtml($end) ?></li>
<?php else: ?>
  <li class="active" title="<?=$this->escapeHtmlAttr($title) ?>"><?=$this->escapeHtml($this->truncate($title, 100)) ?></li>
<?php endif; ?>
<?php $dropdownToggle = '$(\'.dropdown-toggle\').dropdown()'; ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $dropdownToggle, 'SET'); ?>