<?php if (str_contains($this->details['license'], 'publicdomain/mark')): ?>
  <a target="_blank" rel="license" href="<?=$this->details['license'] ?>"><img alt="Public Domain Mark" style="border-width:0" src="https://licensebuttons.net/p/mark/1.0/80x15.png" /></a><br/>
<?php else: ?>
  <?php
    $cctype = [];
    preg_match('/licenses\/([^\/]*)/', $this->details['license'], $cctype);
    $cctype = $cctype[1];
  ?>
  <a target="_blank" rel="license" href="<?=$this->details['license'] ?>deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/<?=$cctype ?>/4.0/80x15.png" /></a><br/>
  This work is licensed under a <a target="_blank" rel="license" href="<?=$this->details['license'] ?>deed.en_US">Creative Commons <?=strpos($cctype, 'by') == 0 ? 'Attribution-' : '' ?><?=strpos($cctype, 'nc') ? 'NonCommercial-' : '' ?><?=strpos($cctype, 'nd') ? 'NoDerivs' : '' ?><?=strpos($cctype, 'sa') ? 'ShareAlike' : '' ?> 4.0 Unported License</a>.
<?php endif; ?>
