<p xmlns:dct="http://purl.org/dc/terms/">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="https://licensebuttons.net/p/zero/1.0/80x15.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <span rel="dct:publisher" resource="[_:publisher]">the person who associated <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a></span>
  with this work has waived all copyright and related or neighboring
  rights to this work.
</p>
