<ul class="nav nav-tabs">
  <li class="static opener">
    <a href="#" onClick="toggleSideNav()" class="hidden">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>
  </li>
  <?php if(in_array('MEDIUM', $this->datastreams)): ?>
    <li class="active"><a href="<?=$this->url('vudl-record', ['id' => $id, 'view' => 'medium']) ?>" data-toggle="tab" data-target="#medium">Medium</a></li>
  <?php endif; ?>
  <?php if(in_array('LARGE', $this->datastreams)): ?>
    <li><a href="<?=$this->url('vudl-record', ['id' => $id, 'view' => 'large']) ?>" data-toggle="tab" data-target="#large">Large</a></li>
    <li><a href="<?=$this->url('vudl-record', ['id' => $id, 'view' => 'zoom']) ?>" data-toggle="tab" data-target="#zoom" class="">Zoom</a></li>
  <?php endif; ?>
  <li><a href="<?=$this->url('vudl-record', ['id' => $id, 'view' => 'master']) ?>" data-toggle="tab" data-target="#master">Downloads</a></li>
</ul>
<div class="tab-content">
  <input type="hidden" id="id-route" src="<?=$this->url('files', ['id' => $id, 'type' => '!!!TYPE!!!']) ?>"/>
  <div class="loading-bar hidden">
    <div class="progress progress-striped active">
      <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
        <span>Loading...</span>
      </div>
    </div>
  </div>
  <?php if(in_array('MEDIUM', $this->datastreams)): ?>
    <div class="tab-pane active" id="medium" aria-hidden="false" tabindex="0">
      <img src="<?=$this->url('files', ['id' => $id, 'type' => 'MEDIUM']) ?>" onLoad="$('.pages .selected.loading').removeClass('loading');"/>
    </div>
  <?php endif; ?>
  <?php if(in_array('LARGE', $this->datastreams)): ?>
    <div class="tab-pane" id="large" aria-hidden="true" tabindex="0">
      <script type="text/template" class="template">
        <img src="<?=$this->url('files', ['id' => $id, 'type' => 'LARGE']) ?>" onLoad="$('.pages .selected.loading').removeClass('loading');"/>
      </script>
    </div>
    <div class="tab-pane" id="zoom">
      <a class="btn btn-default" onClick="Zoomy.turnLeft()"><i class="fa fa-rotate-left"></i></a>
      <a class="btn btn-default" onClick="Zoomy.zoom({deltaY:1})"><i class="fa fa-search-minus"></i></a>
      <a class="btn btn-default" onClick="Zoomy.zoom(0,1)">[1:1]</a>
      <a class="btn btn-default" onClick="Zoomy.toggleMap();$(this).children('.fa').toggleClass('fa fa-toggle-down').toggleClass('fa fa-toggle-up');" title="<?=$this->transEsc('more_info_toggle') ?>">
        <i class="fa fa-toggle-down"></i>
      </a>
      <a class="btn btn-default" onClick="Zoomy.zoom({deltaY:-1})"><i class="fa fa-search-plus"></i></a>
      <a class="btn btn-default" onClick="Zoomy.turnRight()"><i class="fa fa-rotate-right"></i></a><br/>
      <canvas id="zoomy" style="width:100%;height:600px;"></canvas>
    </div>
  <?php endif; ?>
  <div class="tab-pane" id="summary" aria-hidden="true" tabindex="0">
    <?=$this->context($this)->renderInContext('vudl/details.phtml', [])?>
  </div>
  <div class="tab-pane" id="master" aria-hidden="true" tabindex="0">
    <?php if(in_array('MASTER', $this->datastreams)): ?>
      <a id="download-button" href="<?=$this->url('files', ['id' => $this->id, 'type' => 'MASTER']) ?>?download=true" class="btn btn-primary btn-lg">
        <i class="fa fa-download"></i> <?=$this->transEsc('Download File') ?><br>
        <?php if (isset($this->techinfo)): ?>
          <span class="details"><?=$this->techinfo['type'] ?? ''?><?php if(isset($this->techinfo['size'])):?> ~ <?=$this->techinfo['size'] ?><?php endif ?></span>
        <?php endif; ?>
      </a>
    <?php else: ?>
      <p>Original Image File Not Available.</p>
      <p>See below for all available downloads.</p>
    <?php endif; ?>
    <a href="#" id="direct-link" style="margin-top: 0; margin-bottom: 15px;"><i class="fa fa-file-text-o"></i> Permanent Link to This Page</a>
    <div class="accordion" id="techinfo"><?=$this->techinfo['div'] ?? '' ?></div>
  </div>
</div>
<script>
  var routeTemplate = '<?=$this->url('files', ['id' => '!!!ID!!!', 'type' => '!!!TYPE!!!']) ?>';
  function updateView(data) {
    $('.pages .selected.loading').addClass('loading');
    $('.loading-bar').removeClass('hidden');
    var idRoute = routeTemplate.replace('!!!ID!!!', data['id']);
    $('#id-route').attr('src', idRoute);
    $('#medium img').attr('src', idRoute.replace('!!!TYPE!!!', 'MEDIUM'));
    var largeFile = idRoute.replace('!!!TYPE!!!', 'LARGE');
    $('#large img').attr('src', largeFile);
    //Zoomy.load(largeFile);
    current = data;
    if($('#view .nav-tabs li.active a').data('target') === '#zoom') {
      Zoomy.load(largeFile, function(){
        $('.pages .selected.loading').removeClass('loading');
        $('.loading-bar').addClass('hidden');
      });
    } else {
        $('.loading-bar').addClass('hidden');
    }
  }
  $(document).ready(function() {
    var current = <?=json_encode($this->outline['current']) ?>;
    getTechInfo(current);
    $('#view .nav.nav-tabs a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
      var $tab = $($(this).attr('data-target'));
      var template = $tab.find('.template');
      if(template.length > 0) {
        $tab.prepend(template.html());
        template.remove();
      }
    });
    $('#view [data-target="#zoom"]').click(function (e) {
      $('.pages .selected').addClass('loading');
      $('.loading-bar').removeClass('hidden');
      if(!Zoomy.initialized) Zoomy.init(document.getElementById('zoomy'));
      Zoomy.load($('#id-route').attr('src').replace('!!!TYPE!!!', 'LARGE'), function(){
        $('.pages .selected.loading').removeClass('loading');
        $('.loading-bar').addClass('hidden');
      });
    });
    if(['#large', '#zoom', '#master'].indexOf(window.location.hash) > -1) {
      $('#view [data-target="'+window.location.hash+'"]').click();
      $(document).scrollTop(0);
    }
  });
</script>