<?php
  $this->headTitle('Rights Information');
  $this->layout()->breadcrumbs = false;
?>
<style>
  .main h2,
  .main h3 {
    text-align:center;
    margin:.5em;
  }
  .main p {
    text-indent:2em;
  }
</style>
<h2>Rights Information</h2>
<p>
  The use of this material may be subject to the copyright law of the United States
  (Title 17, United States Code) or other third party terms and conditions. The
  person using the material is responsible for any use or infringement of third party
  rights.
</p>

<?php include(__DIR__ . '/disclaimers.phtml'); ?>