<?php
  $this->headTitle('Copyright Information');
  $this->layout()->breadcrumbs = false;
?>
<style>
  .main h2,
  .main h3 {
    text-align:center;
    margin:.5em;
  }
  .main p {
    text-indent:2em;
  }
</style>
<h2>Copyright Information</h2>
<p>
  The Villanova Digital Library contains material--information, facts, opinions,
  statements and objects--provided by the Falvey Memorial Library and by various
  third parties, both individuals and organizations, commercial and otherwise.
  The use of this material is protected by copyright and other laws, rules,
  regulations, and policies governing intellectual property. Unless the terms of
  use are clearly stated with respect to individual items, users must seek
  permission from the copyright owner for all uses that are not allowed by fair
  use and other provisions of the United States Copyright Act. Except as
  otherwise specifically noted, redistribution or commercial use is prohibited
  without express written permission.
</p>

<?php include(__DIR__ . '/disclaimers.phtml'); ?>