<?php
  $skip = [
    'license', 'special_license', 'description', 'title',
  ];
  $no_link = ['title', 'description'];

  $LICENSE_LABELS = [
    'http://creativecommons.org/licenses/by-nc-nd/1.0/' => 'Creative Commons BY-NC-ND 1.0 Generic',
    'http://creativecommons.org/licenses/by-nc-nd/2.0/' => 'Creative Commons BY-NC-ND 2.0 Generic',
    'http://creativecommons.org/licenses/by-nc-nd/3.0/' => 'Creative Commons BY-NC-ND 3.0 Unported',
    'http://creativecommons.org/licenses/by-nc-nd/4.0/' => 'Creative Commons BY-NC-ND 4.0 International',
    'http://creativecommons.org/licenses/by-nc-sa/1.0/' => 'Creative Commons BY-NC-SA 1.0 Generic',
    'http://creativecommons.org/licenses/by-nc-sa/2.0/' => 'Creative Commons BY-NC-SA 2.0 Generic',
    'http://creativecommons.org/licenses/by-nc-sa/3.0/' => 'Creative Commons BY-NC-SA 3.0 Unported',
    'http://creativecommons.org/licenses/by-nc-sa/4.0/' => 'Creative Commons BY-NC-SA 4.0 International',
    'http://creativecommons.org/licenses/by-nc/1.0/' => 'Creative Commons BY-NC 1.0 Generic',
    'http://creativecommons.org/licenses/by-nc/2.0/' => 'Creative Commons BY-NC 2.0 Generic',
    'http://creativecommons.org/licenses/by-nc/3.0/' => 'Creative Commons BY-NC 3.0 Unported',
    'http://creativecommons.org/licenses/by-nc/4.0/' => 'Creative Commons BY-NC 4.0 International',
    'http://creativecommons.org/licenses/by-nd/1.0/' => 'Creative Commons BY-ND 1.0 Generic',
    'http://creativecommons.org/licenses/by-nd/2.0/' => 'Creative Commons BY-ND 2.0 Generic',
    'http://creativecommons.org/licenses/by-nd/3.0/' => 'Creative Commons BY-ND 3.0 Unported',
    'http://creativecommons.org/licenses/by-nd/4.0/' => 'Creative Commons BY-ND 4.0 International',
    'http://creativecommons.org/licenses/by-sa/1.0/' => 'Creative Commons BY-SA 1.0 Generic',
    'http://creativecommons.org/licenses/by-sa/2.0/' => 'Creative Commons BY-SA 2.0 Generic',
    'http://creativecommons.org/licenses/by-sa/3.0/' => 'Creative Commons BY-SA 3.0 Unported',
    'http://creativecommons.org/licenses/by-sa/4.0/' => 'Creative Commons BY-SA 4.0 International',
    'http://creativecommons.org/licenses/by/1.0/' => 'Creative Commons Attribution 1.0 Generic',
    'http://creativecommons.org/licenses/by/2.0/' => 'Creative Commons Attribution 2.0 Generic',
    'http://creativecommons.org/licenses/by/3.0/' => 'Creative Commons Attribution 3.0 Unported',
    'http://creativecommons.org/licenses/by/4.0/' => 'Creative Commons Attribution 4.0 International',
    'http://digital.library.villanova.edu/copyright.html' => 'Villanova University Copyright',
    'https://creativecommons.org/publicdomain/zero/1.0/' => 'CC0 1.0 Universal',
    'https://creativecommons.org/publicdomain/mark/1.0/' => 'Public Domain Mark',
  ];
?>
<?php if (isset($this->details['description'])): ?>
  <p class="description"><?=html_entity_decode($this->details['description']['value'], 2 /*ENT_COMPAT|ENT_HTML401*/, 'UTF-8') ?></p>
<?php endif ?>

<a href="<?=$this->url('record', ['id' => $this->id])?>"><i class="fa fa-list"></i> <?=$this->transEsc('More Details') ?></a><br/>
<a href="<?=$this->url('vudl-record', ['id' => $this->id])?>"><i class="fa fa-book"></i> <?=$this->transEsc('Permanent Link') ?></a><br/><br/>

<table class="table text-left">
  <tr><td><?=$this->transEsc('Full Title') ?></td><td><?=$this->details['title']['value'] ?? '' ?></td></tr>
  <?php foreach ($this->details as $attr => $val): ?>
    <?php
      // Skip items not placed in this table
      if (in_array($attr, $skip)) {
        continue;
      }
    ?>
    <tr><td><?=$this->transEsc($val['title']) ?></td><td>
      <?php // Special format for first_indexed ?>
      <?php if ($attr == 'first_indexed'): ?>
        <?=date_create($val['value'])->format('j F Y') ?>

      <?php // If we need exploding and backlinking ?>
      <?php elseif ($attr == 'topic' || $attr == 'series'): ?>
        <?php
          if (!is_array($val['value'])) {
            $val['value'] = [$val['value']];
          }
        ?>
        <?php if (count($val['value']) > 1): ?><ul class="list-unstyled"><?php endif ?>
        <?php foreach ($val['value'] as $v): ?>
          <?php if (count($val['value']) > 1): ?><li><?php endif ?>
         <?php $parts = explode(' -- ', $v);
            $filter = '';
            foreach ($parts as $i => $p):
              $filter .= ' ' . $p; ?>
              <?=$i > 0 ? ' &gt; ' : '' ?><a class="backlink" href="<?=$this->url('search-results') ?>?filter[]=<?=$attr ?>:<?=urlencode(trim($filter)) ?>"><?=$p ?></a>
         <?php endforeach; ?>
          <?php if (count($val['value']) > 1): ?></li><?php endif ?>
        <?php endforeach; ?>
        <?php if (count($val['value']) > 1): ?></ul><?php endif ?>

      <?php // Items not useful to link ?>
      <?php elseif (in_array($attr, $no_link)): ?>
        <?=is_array($val['value']) ? implode('<br/>', $val['value']) : $val['value'] ?>

      <?php // Array handling ?>
      <?php elseif (is_array($val['value'])): ?>
        <?php if (count($val['value']) == 1): ?>
          <a href="<?=$this->url('search-results') ?>?filter[]=<?=$attr ?>:<?=urlencode($val['value'][0]) ?>"><?=$val['value'][0] ?></a>
        <?php else: ?>
          <ul class="list-unstyled">
          <?php foreach ($val['value'] as $v): ?>
             <li><a href="<?=$this->url('search-results') ?>?filter[]=<?=$attr ?>:<?=urlencode($v) ?>"><?=$v ?></a></li>
          <?php endforeach; ?>
          </ul>
        <?php endif; ?>

      <?php // The rest are linked ?>
      <?php else: ?>
        <a href="<?=$this->url('search-results') ?>?filter[]=<?=$attr ?>:<?=urlencode($val['value']) ?>"><?=$val['value'] ?></a>
      <?php endif; ?>
    </td></tr>
  <?php endforeach; ?>
  <?php if (isset($this->details['license'])): ?>
    <?php if (!$this->details['special_license']): ?>
      <tr>
        <td>License</td>
        <td>
          <a href="<?=$this->details['license'] ?>">
            <?=$LICENSE_LABELS[$this->details['license']] ?? $this->details['license'] ?>
          </a>
        </td>
      </tr>
    <?php endif; ?>
  <?php endif; ?>
</table>
<?php if (isset($this->details['license']) && !empty($this->details['special_license'])): ?>
  <div class="copyright">
    <?=$this->render('/vudl/licenses/' . $this->details['special_license'], ['details' => $this->details]); ?>
  </div>
<?php endif; ?>
