<h3 id="liability">Disclaimer Of Liability</h3>
<p>
  Villanova University makes no warranty, express or implied, and hereby
  disclaims all warranties with regard to the information and materials
  provided, including implied warranties of merchantability, fitness for a
  particular purpose, or non-infringement, and assumes no legal liability or
  responsibility for the accuracy, completeness, currency or usefulness of any
  material displayed or distributed through the Digital Library. Any use or
  reliance upon such information and materials is at your own risk. In no event
  will Villanova University be liable to you or any third party for any damages
  or losses whatsoever resulting from or caused by the Digital Library or its
  contents, or your access or use thereof.
</p>

<h3 id="endorsement">Disclaimer Of Endorsement</h3>
<p>
  Reference herein to any specific opinion, viewpoint, individual, commercial
  product, process, or service by trade name, trademark, manufacturer, or
  otherwise, does not necessarily constitute or imply its endorsement or
  recommendation, or any assertion or evaluation as to its validity or veracity,
  by Villanova University. The views and opinions of authors expressed herein do
  not necessarily state or reflect those of Villanova University and shall not
  be used for advertising or product endorsement purposes.
</p>