<?php
//MOD
  // Set page title.
  $this->headTitle($this->title . ' - ' . $this->itemTitle);

  // Get path to UV (blob to get regardless of versions)
  $uvbase = $this->url('home') . 'themes/vudiglib/assets/' . basename(current(glob(__DIR__ . '/../../assets/uv-*')));

  // Load UV
  $this->headScript()->appendFile("$uvbase/umd/UV.js");
  $this->headLink()->appendStylesheet("$uvbase/uv.css");

  // Customizations
  $this->headLink()->appendStylesheet('uv-custom-v4.css');
  // $this->headScript()->appendFile("$uvbase/lib/offlinenojquery.js");
  // $this->headScript()->appendFile("$uvbase/helpers.js");

  // Multiple breadcrumbs
  $this->layout()->breadcrumbs = $this->render(
      'breadcrumbs/array.phtml',
      [
        'breadcrumbs' => $this->parents,
        'from' => $this->from,
        'end' => $this->breadcrumbEnd,
        'title' => $this->itemTitle,
      ]
  );

  $manifest = $this->serverurl($this->url('vudl-record-manifest', compact('id')));
  $viewerConfig = json_decode(file_get_contents(__DIR__ . '/../../assets/viewer-config.json'));
?>
<style>

</style>
<a id="legacy" href="<?=$this->url('vudl-record', compact('id')) ?>?viewer=legacy" class="pull-right hidden">Switch to old viewer</a>

<?=$this->render('vudl/navigation.phtml'); ?>

<div id="uv" class="uv pdfjs-<?=$viewerConfig->options->usePdfJs ? 'on' : 'off' ?>">
  <noscript>
    <p align="center">Activate Javascript or update your browser for the full Digital Library experience.</p>
    <?php if(false !== $this->prevId || false !== $this->nextId): ?>
      <p align="center">
        <?php if(false !== $this->prevId): ?>
          <a href="<?=$this->url('vudl-record-viewer', ['id' => $this->prevId]) ?>">Previous Page</a>
        <?php endif; ?>
        <?php if(false !== $this->prevId && false !== $this->nextId): ?>
          &ndash;
        <?php endif; ?>
        <?php if(false !== $this->nextId): ?>
          <a href="<?=$this->url('vudl-record-viewer', ['id' => $this->nextId]) ?>">Next Page</a>
        <?php endif; ?>
      </p>
    <?php endif; ?>
    <div class="row">
      <div class="col-sm-3">
        <?php if ($this->currentId): ?>
          <a href="<?=$this->url('files', ['id' => $this->currentId, 'type' => 'LARGE']) ?>">
            <img src="<?=$this->url('files', ['id' => $this->currentId, 'type' => 'MEDIUM']) ?>"/>
          </a>
        <?php endif; ?>
      </div>
      <div class="col-sm-9">
        <table class="table table-striped">
          <?php foreach($this->metadata as $data):  ?>
            <tr>
              <th><?=$data['label']['en'][0] ?></th>
              <td><?=$data['value']['en'][0] ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
      </div>
    </div>
    <?php if(false !== $this->ocr): ?>
      <h3>OCR</h3>
      <div class="ocr">
        <?=$this->escapeHtml($this->ocr) ?>
      </div>
    <?php endif; ?>
  </noscript>
</div>

<div id="loading-modal" class="uv-modal hidden">
  <div class="uv-modal__content">
    <div class="uv-modal__body">
      <p>Loading...</p>
    </div>

    <button id="patience-refresh" class="uv-modal__btn hidden">Refresh</button>
    <button class="uv-modal__btn modal__close">Close</button>
  </div>
</div>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, '/themes/vudiglib/js/vudl/uv-legacy-popover.js', 'SET'); ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, '/themes/vudiglib/js/vudl/uv-setup-v4.js', 'SET'); ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, '/themes/vudiglib/js/vudl/uv-loading-modal.js', 'SET'); ?>
<?php
  $configUri = $this->url('home')
    . 'themes/vudiglib/assets/viewer-config.json?_='
    . filemtime(__DIR__ . '/../../assets/viewer-config.json');
  $viewerOptions = json_encode($viewerConfig->options);
  $js = <<<JS
      // UV v4
      const configUri = "{$configUri}";

      const phpData = {
        root: "../..{$uvbase}",
        manifest: "{$manifest}",
        currentIndex: {$this->currentIndex},
      };

      setupUV4(configUri, phpData, {$viewerOptions});
      JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>
